-- Lighthouse INTEX schema (lighthouse_csv_v7 + ASP.NET Identity)
-- PostgreSQL DDL only — no seed / no INSERT.
-- Source: backend/lighthouse_csv_v7/*.csv column headers + types inferred from data,
--   plus ASP.NET Core Identity tables generated by EF migration.
-- Use as: complete reference for frontend + backend; greenfield `psql -f schema.sql`.

CREATE TABLE safehouses (
    safehouse_id     BIGSERIAL PRIMARY KEY,
    safehouse_code   TEXT NOT NULL,
    name             TEXT NOT NULL,
    region           TEXT,
    city             TEXT,
    province         TEXT,
    country          TEXT,
    open_date        DATE,
    status           TEXT,
    capacity_girls   INTEGER,
    capacity_staff   INTEGER,
    current_occupancy INTEGER,
    notes            TEXT
);

CREATE TABLE supporters (
    supporter_id          BIGSERIAL PRIMARY KEY,
    supporter_type        TEXT NOT NULL,
    display_name          TEXT NOT NULL,
    organization_name     TEXT,
    first_name            TEXT,
    last_name             TEXT,
    relationship_type     TEXT,
    region                TEXT,
    country               TEXT,
    email                 TEXT,
    phone                 TEXT,
    status                TEXT,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    first_donation_date   DATE,
    acquisition_channel   TEXT
);

CREATE TABLE partners (
    partner_id    BIGSERIAL PRIMARY KEY,
    partner_name  TEXT NOT NULL,
    partner_type  TEXT,
    role_type     TEXT,
    contact_name  TEXT,
    email         TEXT,
    phone         TEXT,
    region        TEXT,
    status        TEXT,
    start_date    DATE,
    end_date      DATE,
    notes         TEXT
);

CREATE TABLE social_media_posts (
    post_id                      BIGSERIAL PRIMARY KEY,
    platform                     TEXT,
    platform_post_id             TEXT,
    post_url                     TEXT,
    created_at                   TIMESTAMP WITHOUT TIME ZONE,
    day_of_week                  TEXT,
    post_hour                    INTEGER,
    post_type                    TEXT,
    media_type                   TEXT,
    caption                      TEXT,
    hashtags                     TEXT,
    num_hashtags                 INTEGER,
    mentions_count               INTEGER,
    has_call_to_action           BOOLEAN,
    call_to_action_type          TEXT,
    content_topic                TEXT,
    sentiment_tone               TEXT,
    caption_length               INTEGER,
    features_resident_story      BOOLEAN,
    campaign_name                TEXT,
    is_boosted                   BOOLEAN,
    boost_budget_php             NUMERIC(14, 2),
    impressions                  BIGINT,
    reach                        BIGINT,
    likes                        INTEGER,
    comments                     INTEGER,
    shares                       INTEGER,
    saves                        INTEGER,
    click_throughs               INTEGER,
    video_views                  BIGINT,
    engagement_rate              NUMERIC(10, 6),
    profile_visits               INTEGER,
    donation_referrals           INTEGER,
    estimated_donation_value_php NUMERIC(14, 2),
    follower_count_at_post       INTEGER,
    watch_time_seconds           INTEGER,
    avg_view_duration_seconds    NUMERIC(10, 2),
    subscriber_count_at_post     INTEGER,
    forwards                     NUMERIC(10, 2)
);

CREATE TABLE donations (
    donation_id      BIGSERIAL PRIMARY KEY,
    supporter_id     BIGINT NOT NULL REFERENCES supporters (supporter_id),
    donation_type    TEXT NOT NULL,
    donation_date    DATE,
    is_recurring     BOOLEAN NOT NULL DEFAULT FALSE,
    campaign_name    TEXT,
    channel_source   TEXT,
    currency_code    TEXT,
    amount           NUMERIC(14, 2),
    estimated_value  NUMERIC(14, 2),
    impact_unit      TEXT,
    notes            TEXT,
    referral_post_id BIGINT REFERENCES social_media_posts (post_id)
);

CREATE TABLE donation_allocations (
    allocation_id     BIGSERIAL PRIMARY KEY,
    donation_id       BIGINT NOT NULL REFERENCES donations (donation_id) ON DELETE CASCADE,
    safehouse_id      BIGINT NOT NULL REFERENCES safehouses (safehouse_id),
    program_area      TEXT NOT NULL,
    amount_allocated  NUMERIC(14, 2) NOT NULL,
    allocation_date   DATE NOT NULL,
    allocation_notes  TEXT
);

CREATE TABLE in_kind_donation_items (
    item_id               BIGSERIAL PRIMARY KEY,
    donation_id           BIGINT NOT NULL REFERENCES donations (donation_id) ON DELETE CASCADE,
    item_name             TEXT NOT NULL,
    item_category         TEXT,
    quantity              NUMERIC(14, 2),
    unit_of_measure       TEXT,
    estimated_unit_value  NUMERIC(14, 2),
    intended_use          TEXT,
    received_condition    TEXT
);

CREATE TABLE residents (
    resident_id                  BIGSERIAL PRIMARY KEY,
    case_control_no              TEXT NOT NULL,
    internal_code                TEXT,
    safehouse_id                 BIGINT REFERENCES safehouses (safehouse_id),
    case_status                  TEXT,
    sex                          TEXT,
    date_of_birth                DATE,
    birth_status                 TEXT,
    place_of_birth               TEXT,
    religion                     TEXT,
    case_category                TEXT,
    sub_cat_orphaned             BOOLEAN NOT NULL DEFAULT FALSE,
    sub_cat_trafficked           BOOLEAN NOT NULL DEFAULT FALSE,
    sub_cat_child_labor          BOOLEAN NOT NULL DEFAULT FALSE,
    sub_cat_physical_abuse       BOOLEAN NOT NULL DEFAULT FALSE,
    sub_cat_sexual_abuse         BOOLEAN NOT NULL DEFAULT FALSE,
    sub_cat_osaec                BOOLEAN NOT NULL DEFAULT FALSE,
    sub_cat_cicl                 BOOLEAN NOT NULL DEFAULT FALSE,
    sub_cat_at_risk              BOOLEAN NOT NULL DEFAULT FALSE,
    sub_cat_street_child         BOOLEAN NOT NULL DEFAULT FALSE,
    sub_cat_child_with_hiv       BOOLEAN NOT NULL DEFAULT FALSE,
    is_pwd                       BOOLEAN NOT NULL DEFAULT FALSE,
    pwd_type                     TEXT,
    has_special_needs            BOOLEAN NOT NULL DEFAULT FALSE,
    special_needs_diagnosis      TEXT,
    family_is_4ps                BOOLEAN NOT NULL DEFAULT FALSE,
    family_solo_parent           BOOLEAN NOT NULL DEFAULT FALSE,
    family_indigenous            BOOLEAN NOT NULL DEFAULT FALSE,
    family_parent_pwd            BOOLEAN NOT NULL DEFAULT FALSE,
    family_informal_settler      BOOLEAN NOT NULL DEFAULT FALSE,
    date_of_admission            DATE,
    age_upon_admission           TEXT,
    present_age                  TEXT,
    length_of_stay               TEXT,
    referral_source              TEXT,
    referring_agency_person      TEXT,
    date_colb_registered         DATE,
    date_colb_obtained           DATE,
    assigned_social_worker       TEXT,
    initial_case_assessment      TEXT,
    date_case_study_prepared     DATE,
    reintegration_type           TEXT,
    reintegration_status         TEXT,
    initial_risk_level           TEXT,
    current_risk_level           TEXT,
    date_enrolled                DATE,
    date_closed                  DATE,
    created_at                   TIMESTAMP WITHOUT TIME ZONE,
    notes_restricted             TEXT
);

CREATE TABLE education_records (
    education_record_id BIGSERIAL PRIMARY KEY,
    resident_id         BIGINT NOT NULL REFERENCES residents (resident_id) ON DELETE CASCADE,
    record_date         DATE NOT NULL,
    education_level     TEXT,
    school_name         TEXT,
    enrollment_status   TEXT,
    attendance_rate     NUMERIC(6, 4),
    progress_percent    NUMERIC(6, 2),
    completion_status   TEXT,
    notes               TEXT
);

CREATE TABLE health_wellbeing_records (
    health_record_id           BIGSERIAL PRIMARY KEY,
    resident_id                BIGINT NOT NULL REFERENCES residents (resident_id) ON DELETE CASCADE,
    record_date                DATE NOT NULL,
    general_health_score       NUMERIC(6, 2),
    nutrition_score            NUMERIC(6, 2),
    sleep_quality_score        NUMERIC(6, 2),
    energy_level_score         NUMERIC(6, 2),
    height_cm                  NUMERIC(8, 2),
    weight_kg                  NUMERIC(8, 2),
    bmi                        NUMERIC(8, 2),
    medical_checkup_done       BOOLEAN,
    dental_checkup_done        BOOLEAN,
    psychological_checkup_done BOOLEAN,
    notes                      TEXT
);

CREATE TABLE home_visitations (
    visitation_id             BIGSERIAL PRIMARY KEY,
    resident_id               BIGINT NOT NULL REFERENCES residents (resident_id) ON DELETE CASCADE,
    visit_date                DATE NOT NULL,
    social_worker             TEXT,
    visit_type                TEXT,
    location_visited          TEXT,
    family_members_present    TEXT,
    purpose                   TEXT,
    observations              TEXT,
    family_cooperation_level  TEXT,
    safety_concerns_noted      BOOLEAN,
    follow_up_needed           BOOLEAN,
    follow_up_notes             TEXT,
    visit_outcome               TEXT
);

CREATE TABLE incident_reports (
    incident_id        BIGSERIAL PRIMARY KEY,
    resident_id        BIGINT NOT NULL REFERENCES residents (resident_id) ON DELETE CASCADE,
    safehouse_id       BIGINT REFERENCES safehouses (safehouse_id),
    incident_date      DATE NOT NULL,
    incident_type      TEXT,
    severity           TEXT,
    description        TEXT,
    response_taken     TEXT,
    resolved           BOOLEAN,
    resolution_date    DATE,
    reported_by        TEXT,
    follow_up_required BOOLEAN
);

CREATE TABLE intervention_plans (
    plan_id               BIGSERIAL PRIMARY KEY,
    resident_id           BIGINT NOT NULL REFERENCES residents (resident_id) ON DELETE CASCADE,
    plan_category         TEXT,
    plan_description      TEXT,
    services_provided     TEXT,
    target_value          NUMERIC(14, 4),
    target_date           DATE,
    status                TEXT,
    case_conference_date  DATE,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    updated_at            TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE process_recordings (
    recording_id              BIGSERIAL PRIMARY KEY,
    resident_id               BIGINT NOT NULL REFERENCES residents (resident_id) ON DELETE CASCADE,
    session_date              DATE NOT NULL,
    social_worker             TEXT,
    session_type              TEXT,
    session_duration_minutes  INTEGER,
    emotional_state_observed  TEXT,
    emotional_state_end       TEXT,
    session_narrative         TEXT,
    interventions_applied     TEXT,
    follow_up_actions         TEXT,
    progress_noted              BOOLEAN,
    concerns_flagged          BOOLEAN,
    referral_made             BOOLEAN,
    notes_restricted          TEXT
);

CREATE TABLE partner_assignments (
    assignment_id         BIGSERIAL PRIMARY KEY,
    partner_id            BIGINT NOT NULL REFERENCES partners (partner_id),
    safehouse_id          BIGINT NOT NULL REFERENCES safehouses (safehouse_id),
    program_area          TEXT,
    assignment_start      DATE,
    assignment_end        DATE,
    responsibility_notes  TEXT,
    is_primary            BOOLEAN,
    status                TEXT
);

CREATE TABLE safehouse_monthly_metrics (
    metric_id                  BIGSERIAL PRIMARY KEY,
    safehouse_id               BIGINT NOT NULL REFERENCES safehouses (safehouse_id),
    month_start                DATE NOT NULL,
    month_end                  DATE NOT NULL,
    active_residents           INTEGER,
    avg_education_progress     NUMERIC(8, 2),
    avg_health_score           NUMERIC(8, 2),
    process_recording_count    INTEGER,
    home_visitation_count      INTEGER,
    incident_count             INTEGER,
    notes                      TEXT
);

CREATE TABLE public_impact_snapshots (
    snapshot_id          BIGSERIAL PRIMARY KEY,
    snapshot_date        DATE NOT NULL,
    headline             TEXT,
    summary_text         TEXT,
    metric_payload_json  JSONB,
    is_published         BOOLEAN NOT NULL DEFAULT FALSE,
    published_at         TIMESTAMP WITHOUT TIME ZONE
);

-- INTEX extension: dedicated case conference history (not present as its own CSV in v7)
CREATE TABLE case_conferences (
    conference_id         BIGSERIAL PRIMARY KEY,
    resident_id           BIGINT NOT NULL REFERENCES residents (resident_id) ON DELETE CASCADE,
    conference_date       DATE NOT NULL,
    conference_type       TEXT,
    summary               TEXT,
    decisions_made        TEXT,
    next_steps            TEXT,
    next_conference_date  DATE,
    created_by            TEXT
);

-- INTEX extension: ML pipeline refresh outputs published from the nightly retrain job
CREATE TABLE ml_pipeline_runs (
    run_id        BIGSERIAL PRIMARY KEY,
    pipeline_name TEXT NOT NULL,
    display_name  TEXT,
    model_name    TEXT,
    status        TEXT NOT NULL DEFAULT 'completed',
    trained_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_source   TEXT,
    source_commit TEXT,
    metrics_json  JSONB,
    manifest_json JSONB
);

CREATE TABLE ml_prediction_snapshots (
    prediction_id     BIGSERIAL PRIMARY KEY,
    run_id            BIGINT NOT NULL REFERENCES ml_pipeline_runs (run_id) ON DELETE CASCADE,
    pipeline_name     TEXT NOT NULL,
    entity_type       TEXT NOT NULL,
    entity_id         BIGINT,
    entity_key        TEXT NOT NULL,
    entity_label      TEXT,
    safehouse_id      BIGINT,
    record_timestamp  TIMESTAMPTZ,
    prediction_value  INTEGER,
    prediction_score  DOUBLE PRECISION NOT NULL,
    rank_order        INTEGER NOT NULL,
    context_json      JSONB,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_donations_supporter ON donations (supporter_id);
CREATE INDEX idx_donation_allocations_donation ON donation_allocations (donation_id);
CREATE INDEX idx_residents_safehouse ON residents (safehouse_id);
CREATE INDEX idx_case_conferences_resident ON case_conferences (resident_id);
CREATE INDEX idx_ml_pipeline_runs_pipeline_time
    ON ml_pipeline_runs (pipeline_name, trained_at DESC);
CREATE INDEX idx_ml_prediction_snapshots_run_rank
    ON ml_prediction_snapshots (run_id, rank_order);
CREATE INDEX idx_ml_prediction_snapshots_pipeline_entity
    ON ml_prediction_snapshots (pipeline_name, entity_id);

-- ---------------------------------------------------------------------------
-- ASP.NET Core Identity tables
-- ---------------------------------------------------------------------------

CREATE TABLE "AspNetRoles" (
    "Id"                text        NOT NULL PRIMARY KEY,
    "Name"              varchar(256),
    "NormalizedName"    varchar(256),
    "ConcurrencyStamp"  text
);

CREATE TABLE "AspNetUsers" (
    "Id"                    text        NOT NULL PRIMARY KEY,
    "FullName"              text,
    "UserName"              varchar(256),
    "NormalizedUserName"    varchar(256),
    "Email"                 varchar(256),
    "NormalizedEmail"       varchar(256),
    "EmailConfirmed"        boolean     NOT NULL DEFAULT FALSE,
    "PasswordHash"          text,
    "SecurityStamp"         text,
    "ConcurrencyStamp"      text,
    "PhoneNumber"           text,
    "PhoneNumberConfirmed"  boolean     NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled"      boolean     NOT NULL DEFAULT FALSE,
    "LockoutEnd"            timestamptz,
    "LockoutEnabled"        boolean     NOT NULL DEFAULT FALSE,
    "AccessFailedCount"     integer     NOT NULL DEFAULT 0
);

CREATE TABLE "AspNetRoleClaims" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId"    text    NOT NULL REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    "ClaimType" text,
    "ClaimValue" text
);

CREATE TABLE "AspNetUserClaims" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"    text    NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "ClaimType" text,
    "ClaimValue" text
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider"         text NOT NULL,
    "ProviderKey"           text NOT NULL,
    "ProviderDisplayName"   text,
    "UserId"                text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "RoleId" text NOT NULL REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE "AspNetUserTokens" (
    "UserId"        text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "LoginProvider" text NOT NULL,
    "Name"          text NOT NULL,
    "Value"         text,
    PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

CREATE UNIQUE INDEX "RoleNameIndex"    ON "AspNetRoles" ("NormalizedName");
CREATE INDEX "IX_AspNetRoleClaims_RoleId"  ON "AspNetRoleClaims" ("RoleId");
CREATE INDEX "IX_AspNetUserClaims_UserId"  ON "AspNetUserClaims" ("UserId");
CREATE INDEX "IX_AspNetUserLogins_UserId"  ON "AspNetUserLogins" ("UserId");
CREATE INDEX "IX_AspNetUserRoles_RoleId"   ON "AspNetUserRoles" ("RoleId");
CREATE INDEX "EmailIndex"              ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex"    ON "AspNetUsers" ("NormalizedUserName");

-- ---------------------------------------------------------------------------
-- INTEX Identity extensions
-- ---------------------------------------------------------------------------

ALTER TABLE supporters
    ADD COLUMN IF NOT EXISTS identity_user_id varchar(450);
ALTER TABLE supporters
    ADD COLUMN IF NOT EXISTS can_login boolean NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS idx_supporters_identity_user
    ON supporters (identity_user_id)
    WHERE identity_user_id IS NOT NULL;

CREATE TABLE staff_safehouse_assignments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         varchar(450) NOT NULL,
    safehouse_id    bigint       NOT NULL REFERENCES safehouses (safehouse_id) ON DELETE CASCADE,
    UNIQUE (user_id, safehouse_id)
);
CREATE INDEX ix_staff_safehouse_assignments_safehouse
    ON staff_safehouse_assignments (safehouse_id);
