// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using intex.Data;

#nullable disable

namespace intex.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406222639_AddIdentityAndStaffAssignments")]
    partial class AddIdentityAndStaffAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("intex.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("intex.Data.Entities.CaseConference", b =>
                {
                    b.Property<long>("ConferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("conference_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ConferenceId"));

                    b.Property<DateOnly>("ConferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("conference_date");

                    b.Property<string>("ConferenceType")
                        .HasColumnType("text")
                        .HasColumnName("conference_type");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DecisionsMade")
                        .HasColumnType("text")
                        .HasColumnName("decisions_made");

                    b.Property<DateOnly?>("NextConferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("next_conference_date");

                    b.Property<string>("NextSteps")
                        .HasColumnType("text")
                        .HasColumnName("next_steps");

                    b.Property<long>("ResidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("resident_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("ConferenceId");

                    b.ToTable("case_conferences");
                });

            modelBuilder.Entity("intex.Data.Entities.Donation", b =>
                {
                    b.Property<long>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("donation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DonationId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("CampaignName")
                        .HasColumnType("text")
                        .HasColumnName("campaign_name");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("text")
                        .HasColumnName("channel_source");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly?>("DonationDate")
                        .HasColumnType("date")
                        .HasColumnName("donation_date");

                    b.Property<string>("DonationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("donation_type");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_value");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("text")
                        .HasColumnName("impact_unit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long?>("ReferralPostId")
                        .HasColumnType("bigint")
                        .HasColumnName("referral_post_id");

                    b.Property<long>("SupporterId")
                        .HasColumnType("bigint")
                        .HasColumnName("supporter_id");

                    b.HasKey("DonationId");

                    b.ToTable("donations");
                });

            modelBuilder.Entity("intex.Data.Entities.DonationAllocation", b =>
                {
                    b.Property<long>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("allocation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AllocationId"));

                    b.Property<DateOnly>("AllocationDate")
                        .HasColumnType("date")
                        .HasColumnName("allocation_date");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("text")
                        .HasColumnName("allocation_notes");

                    b.Property<decimal>("AmountAllocated")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_allocated");

                    b.Property<long>("DonationId")
                        .HasColumnType("bigint")
                        .HasColumnName("donation_id");

                    b.Property<string>("ProgramArea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_area");

                    b.Property<long>("SafehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("safehouse_id");

                    b.HasKey("AllocationId");

                    b.ToTable("donation_allocations");
                });

            modelBuilder.Entity("intex.Data.Entities.EducationRecord", b =>
                {
                    b.Property<long>("EducationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("education_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EducationRecordId"));

                    b.Property<decimal?>("AttendanceRate")
                        .HasColumnType("numeric")
                        .HasColumnName("attendance_rate");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("text")
                        .HasColumnName("completion_status");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("text")
                        .HasColumnName("education_level");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("text")
                        .HasColumnName("enrollment_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("ProgressPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("progress_percent");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<long>("ResidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("resident_id");

                    b.Property<string>("SchoolName")
                        .HasColumnType("text")
                        .HasColumnName("school_name");

                    b.HasKey("EducationRecordId");

                    b.ToTable("education_records");
                });

            modelBuilder.Entity("intex.Data.Entities.HealthWellbeingRecord", b =>
                {
                    b.Property<long>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("health_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("HealthRecordId"));

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("numeric")
                        .HasColumnName("bmi");

                    b.Property<bool?>("DentalCheckupDone")
                        .HasColumnType("boolean")
                        .HasColumnName("dental_checkup_done");

                    b.Property<decimal?>("EnergyLevelScore")
                        .HasColumnType("numeric")
                        .HasColumnName("energy_level_score");

                    b.Property<decimal?>("GeneralHealthScore")
                        .HasColumnType("numeric")
                        .HasColumnName("general_health_score");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("numeric")
                        .HasColumnName("height_cm");

                    b.Property<bool?>("MedicalCheckupDone")
                        .HasColumnType("boolean")
                        .HasColumnName("medical_checkup_done");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("NutritionScore")
                        .HasColumnType("numeric")
                        .HasColumnName("nutrition_score");

                    b.Property<bool?>("PsychologicalCheckupDone")
                        .HasColumnType("boolean")
                        .HasColumnName("psychological_checkup_done");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<long>("ResidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("resident_id");

                    b.Property<decimal?>("SleepQualityScore")
                        .HasColumnType("numeric")
                        .HasColumnName("sleep_quality_score");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kg");

                    b.HasKey("HealthRecordId");

                    b.ToTable("health_wellbeing_records");
                });

            modelBuilder.Entity("intex.Data.Entities.HomeVisitation", b =>
                {
                    b.Property<long>("VisitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("visitation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VisitationId"));

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("text")
                        .HasColumnName("family_cooperation_level");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("text")
                        .HasColumnName("family_members_present");

                    b.Property<bool?>("FollowUpNeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("follow_up_needed");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("text")
                        .HasColumnName("follow_up_notes");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("text")
                        .HasColumnName("location_visited");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<long>("ResidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("resident_id");

                    b.Property<bool?>("SafetyConcernsNoted")
                        .HasColumnType("boolean")
                        .HasColumnName("safety_concerns_noted");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("text")
                        .HasColumnName("social_worker");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("text")
                        .HasColumnName("visit_outcome");

                    b.Property<string>("VisitType")
                        .HasColumnType("text")
                        .HasColumnName("visit_type");

                    b.HasKey("VisitationId");

                    b.ToTable("home_visitations");
                });

            modelBuilder.Entity("intex.Data.Entities.InKindDonationItem", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemId"));

                    b.Property<long>("DonationId")
                        .HasColumnType("bigint")
                        .HasColumnName("donation_id");

                    b.Property<decimal?>("EstimatedUnitValue")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_unit_value");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("text")
                        .HasColumnName("intended_use");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("text")
                        .HasColumnName("item_category");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("text")
                        .HasColumnName("received_condition");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("text")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("ItemId");

                    b.ToTable("in_kind_donation_items");
                });

            modelBuilder.Entity("intex.Data.Entities.IncidentReport", b =>
                {
                    b.Property<long>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("incident_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IncidentId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("FollowUpRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("follow_up_required");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("date")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .HasColumnType("text")
                        .HasColumnName("incident_type");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("text")
                        .HasColumnName("reported_by");

                    b.Property<long>("ResidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("date")
                        .HasColumnName("resolution_date");

                    b.Property<bool?>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("text")
                        .HasColumnName("response_taken");

                    b.Property<long?>("SafehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Severity")
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.HasKey("IncidentId");

                    b.ToTable("incident_reports");
                });

            modelBuilder.Entity("intex.Data.Entities.InterventionPlan", b =>
                {
                    b.Property<long>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlanId"));

                    b.Property<DateOnly?>("CaseConferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("case_conference_date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanCategory")
                        .HasColumnType("text")
                        .HasColumnName("plan_category");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("text")
                        .HasColumnName("plan_description");

                    b.Property<long>("ResidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("resident_id");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("text")
                        .HasColumnName("services_provided");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("numeric")
                        .HasColumnName("target_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlanId");

                    b.ToTable("intervention_plans");
                });

            modelBuilder.Entity("intex.Data.Entities.Partner", b =>
                {
                    b.Property<long>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("partner_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PartnerId"));

                    b.Property<string>("ContactName")
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partner_name");

                    b.Property<string>("PartnerType")
                        .HasColumnType("text")
                        .HasColumnName("partner_type");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RoleType")
                        .HasColumnType("text")
                        .HasColumnName("role_type");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("PartnerId");

                    b.ToTable("partners");
                });

            modelBuilder.Entity("intex.Data.Entities.PartnerAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AssignmentId"));

                    b.Property<DateOnly?>("AssignmentEnd")
                        .HasColumnType("date")
                        .HasColumnName("assignment_end");

                    b.Property<DateOnly?>("AssignmentStart")
                        .HasColumnType("date")
                        .HasColumnName("assignment_start");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<long>("PartnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("partner_id");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("text")
                        .HasColumnName("program_area");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("text")
                        .HasColumnName("responsibility_notes");

                    b.Property<long?>("SafehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("AssignmentId");

                    b.ToTable("partner_assignments");
                });

            modelBuilder.Entity("intex.Data.Entities.ProcessRecording", b =>
                {
                    b.Property<long>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("recording_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordingId"));

                    b.Property<bool?>("ConcernsFlagged")
                        .HasColumnType("boolean")
                        .HasColumnName("concerns_flagged");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("text")
                        .HasColumnName("emotional_state_end");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("text")
                        .HasColumnName("emotional_state_observed");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("text")
                        .HasColumnName("follow_up_actions");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("text")
                        .HasColumnName("interventions_applied");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("text")
                        .HasColumnName("notes_restricted");

                    b.Property<bool?>("ProgressNoted")
                        .HasColumnType("boolean")
                        .HasColumnName("progress_noted");

                    b.Property<bool?>("ReferralMade")
                        .HasColumnType("boolean")
                        .HasColumnName("referral_made");

                    b.Property<long>("ResidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("session_duration_minutes");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("text")
                        .HasColumnName("session_narrative");

                    b.Property<string>("SessionType")
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("text")
                        .HasColumnName("social_worker");

                    b.HasKey("RecordingId");

                    b.ToTable("process_recordings");
                });

            modelBuilder.Entity("intex.Data.Entities.PublicImpactSnapshot", b =>
                {
                    b.Property<long>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SnapshotId"));

                    b.Property<string>("Headline")
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metric_payload_json");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("SummaryText")
                        .HasColumnType("text")
                        .HasColumnName("summary_text");

                    b.HasKey("SnapshotId");

                    b.ToTable("public_impact_snapshots");
                });

            modelBuilder.Entity("intex.Data.Entities.Resident", b =>
                {
                    b.Property<long>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("resident_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ResidentId"));

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("text")
                        .HasColumnName("age_upon_admission");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("text")
                        .HasColumnName("assigned_social_worker");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("text")
                        .HasColumnName("birth_status");

                    b.Property<string>("CaseCategory")
                        .HasColumnType("text")
                        .HasColumnName("case_category");

                    b.Property<string>("CaseControlNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_control_no");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("text")
                        .HasColumnName("case_status");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("text")
                        .HasColumnName("current_risk_level");

                    b.Property<DateOnly?>("DateCaseStudyPrepared")
                        .HasColumnType("date")
                        .HasColumnName("date_case_study_prepared");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("date")
                        .HasColumnName("date_closed");

                    b.Property<DateOnly?>("DateColbObtained")
                        .HasColumnType("date")
                        .HasColumnName("date_colb_obtained");

                    b.Property<DateOnly?>("DateColbRegistered")
                        .HasColumnType("date")
                        .HasColumnName("date_colb_registered");

                    b.Property<DateOnly?>("DateEnrolled")
                        .HasColumnType("date")
                        .HasColumnName("date_enrolled");

                    b.Property<DateOnly?>("DateOfAdmission")
                        .HasColumnType("date")
                        .HasColumnName("date_of_admission");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<bool>("FamilyIndigenous")
                        .HasColumnType("boolean")
                        .HasColumnName("family_indigenous");

                    b.Property<bool>("FamilyInformalSettler")
                        .HasColumnType("boolean")
                        .HasColumnName("family_informal_settler");

                    b.Property<bool>("FamilyIs4ps")
                        .HasColumnType("boolean")
                        .HasColumnName("family_is_4ps");

                    b.Property<bool>("FamilyParentPwd")
                        .HasColumnType("boolean")
                        .HasColumnName("family_parent_pwd");

                    b.Property<bool>("FamilySoloParent")
                        .HasColumnType("boolean")
                        .HasColumnName("family_solo_parent");

                    b.Property<bool>("HasSpecialNeeds")
                        .HasColumnType("boolean")
                        .HasColumnName("has_special_needs");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("text")
                        .HasColumnName("initial_case_assessment");

                    b.Property<string>("InitialRiskLevel")
                        .HasColumnType("text")
                        .HasColumnName("initial_risk_level");

                    b.Property<string>("InternalCode")
                        .HasColumnType("text")
                        .HasColumnName("internal_code");

                    b.Property<bool>("IsPwd")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pwd");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("text")
                        .HasColumnName("length_of_stay");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("text")
                        .HasColumnName("notes_restricted");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("PresentAge")
                        .HasColumnType("text")
                        .HasColumnName("present_age");

                    b.Property<string>("PwdType")
                        .HasColumnType("text")
                        .HasColumnName("pwd_type");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("text")
                        .HasColumnName("referral_source");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("text")
                        .HasColumnName("referring_agency_person");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("text")
                        .HasColumnName("reintegration_status");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("text")
                        .HasColumnName("reintegration_type");

                    b.Property<string>("Religion")
                        .HasColumnType("text")
                        .HasColumnName("religion");

                    b.Property<long?>("SafehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("special_needs_diagnosis");

                    b.Property<bool>("SubCatAtRisk")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_at_risk");

                    b.Property<bool>("SubCatChildLabor")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_child_labor");

                    b.Property<bool>("SubCatChildWithHiv")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_child_with_hiv");

                    b.Property<bool>("SubCatCicl")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_cicl");

                    b.Property<bool>("SubCatOrphaned")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_orphaned");

                    b.Property<bool>("SubCatOsaec")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_osaec");

                    b.Property<bool>("SubCatPhysicalAbuse")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_physical_abuse");

                    b.Property<bool>("SubCatSexualAbuse")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_sexual_abuse");

                    b.Property<bool>("SubCatStreetChild")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_street_child");

                    b.Property<bool>("SubCatTrafficked")
                        .HasColumnType("boolean")
                        .HasColumnName("sub_cat_trafficked");

                    b.HasKey("ResidentId");

                    b.ToTable("residents");
                });

            modelBuilder.Entity("intex.Data.Entities.Safehouse", b =>
                {
                    b.Property<long>("SafehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("safehouse_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SafehouseId"));

                    b.Property<int?>("CapacityGirls")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_girls");

                    b.Property<int?>("CapacityStaff")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_staff");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("integer")
                        .HasColumnName("current_occupancy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("OpenDate")
                        .HasColumnType("date")
                        .HasColumnName("open_date");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("SafehouseCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("safehouse_code");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("SafehouseId");

                    b.ToTable("safehouses");
                });

            modelBuilder.Entity("intex.Data.Entities.SafehouseMonthlyMetric", b =>
                {
                    b.Property<long>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("metric_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MetricId"));

                    b.Property<int?>("ActiveResidents")
                        .HasColumnType("integer")
                        .HasColumnName("active_residents");

                    b.Property<decimal?>("AvgEducationProgress")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_education_progress");

                    b.Property<decimal?>("AvgHealthScore")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_health_score");

                    b.Property<int?>("HomeVisitationCount")
                        .HasColumnType("integer")
                        .HasColumnName("home_visitation_count");

                    b.Property<int?>("IncidentCount")
                        .HasColumnType("integer")
                        .HasColumnName("incident_count");

                    b.Property<DateOnly>("MonthEnd")
                        .HasColumnType("date")
                        .HasColumnName("month_end");

                    b.Property<DateOnly>("MonthStart")
                        .HasColumnType("date")
                        .HasColumnName("month_start");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("ProcessRecordingCount")
                        .HasColumnType("integer")
                        .HasColumnName("process_recording_count");

                    b.Property<long>("SafehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("safehouse_id");

                    b.HasKey("MetricId");

                    b.ToTable("safehouse_monthly_metrics");
                });

            modelBuilder.Entity("intex.Data.Entities.SocialMediaPost", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PostId"));

                    b.Property<decimal?>("AvgViewDurationSeconds")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_view_duration_seconds");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasColumnType("numeric")
                        .HasColumnName("boost_budget_php");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("text")
                        .HasColumnName("call_to_action_type");

                    b.Property<string>("CampaignName")
                        .HasColumnType("text")
                        .HasColumnName("campaign_name");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<int?>("CaptionLength")
                        .HasColumnType("integer")
                        .HasColumnName("caption_length");

                    b.Property<int?>("ClickThroughs")
                        .HasColumnType("integer")
                        .HasColumnName("click_throughs");

                    b.Property<int?>("Comments")
                        .HasColumnType("integer")
                        .HasColumnName("comments");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("text")
                        .HasColumnName("content_topic");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<int?>("DonationReferrals")
                        .HasColumnType("integer")
                        .HasColumnName("donation_referrals");

                    b.Property<decimal?>("EngagementRate")
                        .HasColumnType("numeric")
                        .HasColumnName("engagement_rate");

                    b.Property<decimal?>("EstimatedDonationValuePhp")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_donation_value_php");

                    b.Property<bool?>("FeaturesResidentStory")
                        .HasColumnType("boolean")
                        .HasColumnName("features_resident_story");

                    b.Property<int?>("FollowerCountAtPost")
                        .HasColumnType("integer")
                        .HasColumnName("follower_count_at_post");

                    b.Property<decimal?>("Forwards")
                        .HasColumnType("numeric")
                        .HasColumnName("forwards");

                    b.Property<bool?>("HasCallToAction")
                        .HasColumnType("boolean")
                        .HasColumnName("has_call_to_action");

                    b.Property<string>("Hashtags")
                        .HasColumnType("text")
                        .HasColumnName("hashtags");

                    b.Property<long?>("Impressions")
                        .HasColumnType("bigint")
                        .HasColumnName("impressions");

                    b.Property<bool?>("IsBoosted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_boosted");

                    b.Property<int?>("Likes")
                        .HasColumnType("integer")
                        .HasColumnName("likes");

                    b.Property<string>("MediaType")
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<int?>("MentionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("mentions_count");

                    b.Property<int?>("NumHashtags")
                        .HasColumnType("integer")
                        .HasColumnName("num_hashtags");

                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("text")
                        .HasColumnName("platform_post_id");

                    b.Property<int?>("PostHour")
                        .HasColumnType("integer")
                        .HasColumnName("post_hour");

                    b.Property<string>("PostType")
                        .HasColumnType("text")
                        .HasColumnName("post_type");

                    b.Property<string>("PostUrl")
                        .HasColumnType("text")
                        .HasColumnName("post_url");

                    b.Property<int?>("ProfileVisits")
                        .HasColumnType("integer")
                        .HasColumnName("profile_visits");

                    b.Property<long?>("Reach")
                        .HasColumnType("bigint")
                        .HasColumnName("reach");

                    b.Property<int?>("Saves")
                        .HasColumnType("integer")
                        .HasColumnName("saves");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("text")
                        .HasColumnName("sentiment_tone");

                    b.Property<int?>("Shares")
                        .HasColumnType("integer")
                        .HasColumnName("shares");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("integer")
                        .HasColumnName("subscriber_count_at_post");

                    b.Property<long?>("VideoViews")
                        .HasColumnType("bigint")
                        .HasColumnName("video_views");

                    b.Property<int?>("WatchTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("watch_time_seconds");

                    b.HasKey("PostId");

                    b.ToTable("social_media_posts");
                });

            modelBuilder.Entity("intex.Data.Entities.StaffSafehouseAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("SafehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SafehouseId");

                    b.HasIndex("UserId", "SafehouseId")
                        .IsUnique();

                    b.ToTable("staff_safehouse_assignments");
                });

            modelBuilder.Entity("intex.Data.Entities.Supporter", b =>
                {
                    b.Property<long>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("supporter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SupporterId"));

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("text")
                        .HasColumnName("acquisition_channel");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("boolean")
                        .HasColumnName("can_login");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FirstDonationDate")
                        .HasColumnType("date")
                        .HasColumnName("first_donation_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("identity_user_id");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("text")
                        .HasColumnName("organization_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("text")
                        .HasColumnName("relationship_type");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SupporterType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supporter_type");

                    b.HasKey("SupporterId");

                    b.ToTable("supporters");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("intex.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("intex.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("intex.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("intex.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("intex.Data.Entities.StaffSafehouseAssignment", b =>
                {
                    b.HasOne("intex.Data.Entities.Safehouse", "Safehouse")
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Safehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
